FROM ubuntu:latest
FROM python:3
MAINTAINER Justin Hilliard "justin.a.hilliard@gmail.com"
RUN apt-get update -y
RUN apt-get install -y python-pip python-dev build-essential libmysqlclient-dev
RUN pip install --upgrade pip
COPY dependencies /dependencies
RUN pip install -r dependencies/requirements.txt
COPY src /src
COPY config_production /config
COPY src/platform/App.py App.py
CMD ["python3", "App.py"]